server:
	cargo run --bin main --release

create_db:
	cargo run --bin create_table --release

create_json:
	cargo run --bin create_json --release

sample:
	cargo run --bin test --release

model:
	cargo run --bin test_model --release